### ISSUE TITLE
关于淘宝联盟接口返回数据处理的问题

### ISSUE THREAD

**Issue by hainuo** [dataoke/tbk-union-sdk#2]
https://github.com/dataoke/tbk-union-sdk/blob/b644ef7116243fb263803e1be3d921b1ad5cee9c/src/Tools/GateWay.php#L73-L74

这一段对错误的处理有点不友好，
当我根据readme来测试接口时报错：
`15    Remote service error`
我以为是错误的是curl出错了  最后打印了返回值
```
[code] => 15
    [msg] => Remote service error
    [sub_code] => 2
    [sub_msg] => pid不正确，请检查是否输入了正确的adzoneId和siteId
    [request_id] => 64jynw0jsbja
```
才发现 原来是返回数据处理没将信息处理好

**Comment by yumufeng** [comment]
返回false了的，就说明出错啦，可以根据错误码，在淘宝文档看到对应信息

**Comment by yumufeng** [comment]
已调整优化
